pipeline {
    agent any
    stages {
        stage("gitPull") {
            steps {
                dir('SpringDataJpa') {
                    git branch: 'master',
                    url: 'https://github.com/yywzt/SpringDataJpa.git'
                }
            }
        }
        stage('testAndBuild') {
            steps {
                dir('SpringDataJpa') {
                    sh label: '', script: 'mvn clean install'
                }
            }
        }
        stage('deploy') {
            steps {
                sshPublisher(
                    publishers: [
                        sshPublisherDesc(
                            configName: 'centos002',
                            transfers:[
                                sshTransfer(
                                    sourceFiles: 'target/*.jar',
                                    removePrefix: 'target/*.jar',
                                    remoteDirectory: '/yw/jar/',
                                    execCommand: 'echo "build success"',
                                    remoteDirectorySDF: false,
                                    cleanRemote: true,
                                    flatten: false
                                )
                            ],
                            usePromotionTimestamp: false,
                            useWorkspaceInPromotion: false,
                            verbose: false
                        )
                    ]
                )
            }
        }
    }
    post {
        failure {
            emailext(
                subject: "Jenkins Job Failed: ${currentBuild.fullDisplayName}",
                body: "<b>Something is wrong </b><br>Project: ${env.JOB_NAME} <br>Build Number: #${env.BUILD_NUMBER} <br> URL build: ${env.BUILD_URL}.",
                mimeType: 'text/html',
                to: '2507967396@qq.com;')
        }
    }
}